/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "activityIndicator": { "creationFunction": "CreateActivityIndicator" },
    "browser": { "creationFunction": "CreateBrowser" },
    "button": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 60, "leftImageWidth": 16, "rightImageWidth": 5, "text": "Back" },
    "button1": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 60, "leftImageWidth": 5, "rightImageWidth": 16, "text": "Next" },
    "button2": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 80, "leftImageWidth": 15, "rightImageWidth": 1, "text": "Button" },
    "button3": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 80, "leftImageWidth": 15, "rightImageWidth": 15, "text": "Button" },
    "button4": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 80, "leftImageWidth": 1, "rightImageWidth": 15, "text": "Button" },
    "button5": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 309, "leftImageWidth": 5, "rightImageWidth": 5, "text": "Button" },
    "button6": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 143, "leftImageWidth": 5, "rightImageWidth": 1, "text": "Button" },
    "button7": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 157, "leftImageWidth": 1, "rightImageWidth": 5, "text": "Button" },
    "button8": { "creationFunction": "CreatePushButton", "initialHeight": 30, "initialWidth": 70, "leftImageWidth": 16, "rightImageWidth": 5, "text": "Back" },
    "callButton": { "creationFunction": "CreateCallButton", "customImage": "Images/callGlyph.png", "customImagePosition": "PushButton.IMAGE_POSITION_CENTER", "customImagePressed": "Images/callGlyph.png", "initialHeight": 36, "initialWidth": 36, "leftImageWidth": 6, "rightImageWidth": 6, "text": "" },
    "footer": { "creationFunction": "CreateText", "text": "Developed with Dashcode" },
    "gauge": { "continuous": true, "creationFunction": "CreateGauge", "criticalValue": 80, "interactive": true, "maxValue": 100, "onValue": 1, "pivotOffsetX": 28, "pivotOffsetY": 28, "pointerReach": 85, "startAngle": 45, "stopAngle": 315, "warningValue": 50 },
    "header": { "creationFunction": "CreateHeader", "rootTitle": "Home" },
    "horizontalLevelIndicator": { "creationFunction": "CreateHorizontalLevelIndicator", "criticalValue": 15, "imageHeight": 20, "imageWidth": 12, "maxValue": 20, "onValue": 1, "warningValue": 10 },
    "indicator": { "creationFunction": "CreateIndicator", "criticalValue": 15, "onValue": 1, "warningValue": 10 },
    "label": { "creationFunction": "CreateText", "text": "Item" },
    "label1": { "creationFunction": "CreateText", "text": "Item" },
    "list": { "creationFunction": "CreateList", "dataArray": ["Item 1", "Item 2", "Item 3"], "labelElementId": "label", "listStyle": "List.EDGE_TO_EDGE", "sampleRows": 3 },
    "list1": { "creationFunction": "CreateList", "dataArray": ["Item 1", "Item 2", "Item 3"], "labelElementId": "label1", "listStyle": "List.ROUNDED_RECTANGLE", "sampleRows": 3 },
    "mailButton": { "creationFunction": "CreateMailButton", "customImage": "Images/mailGlyph.png", "customImagePosition": "PushButton.IMAGE_POSITION_CENTER", "customImagePressed": "Images/mailGlyph.png", "initialHeight": 36, "initialWidth": 36, "leftImageWidth": 6, "rightImageWidth": 6, "text": "" },
    "mapButton": { "creationFunction": "CreateMapButton", "customImage": "Images/mapGlyph.png", "customImagePosition": "PushButton.IMAGE_POSITION_CENTER", "customImagePressed": "Images/mapGlyph.png", "initialHeight": 36, "initialWidth": 36, "leftImageWidth": 6, "rightImageWidth": 6, "text": "" },
    "stackLayout": { "creationFunction": "CreateStackLayout", "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }] },
    "stackLayout1": { "creationFunction": "CreateStackLayout", "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }] },
    "text5": { "creationFunction": "CreateText", "text": "Text" },
    "verticalLevelIndicator": { "creationFunction": "CreateVerticalLevelIndicator", "criticalValue": 15, "imageHeight": 12, "imageWidth": 20, "maxValue": 20, "onValue": 1, "warningValue": 10 }
};
